#1. Why does this feature selection with chi2 fail?
from sklearn.feature_selection import SelectKBest, chi2

X = [[-1, 2, 3], [4, 0, -6], [7, 8, 9], [1, 2, 3]]
y = [0, 1, 0, 1]

selector = SelectKBest(score_func=chi2, k=2)
X_new = selector.fit_transform(X, y)


In [1]:
#1. Why does this feature selection with chi2 fail? Chi2 should have non-negative value
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.preprocessing import MinMaxScaler

X = [[-1, 2, 3], [4, 0, -6], [7, 8, 9], [1, 2, 3]]
y = [0, 1, 0, 1]

sc=MinMaxScaler()
x=sc.fit_transform(X)
selector = SelectKBest(score_func=chi2, k=2)
X_new = selector.fit_transform(x, y)
X_new

array([[0.25, 0.6 ],
       [0.  , 0.  ],
       [1.  , 1.  ],
       [0.25, 0.6 ]])

#2.
from sklearn.metrics.pairwise import cosine_similarity

# Error: strings instead of numerical features
user1 = ['action', 'comedy', 'romance']
user2 = ['action', 'thriller', 'comedy']

similarity = cosine_similarity([user1], [user2])


In [2]:
#2.
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd

# Error: strings instead of numerical features
user1 = ['action', 'comedy', 'romance']
user2 = ['action', 'thriller', 'comedy']

user1=pd.get_dummies(user1,drop_first=True,dtype=int)
user2=pd.get_dummies(user2,drop_first=True,dtype=int)

similarity = cosine_similarity(user1, user2)
similarity

array([[0., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

#3.
from sklearn.decomposition import PCA

X = [[1, 2], [3, 4], [5, 6]]
pca = PCA(n_components=5)  # more components than features
X_new = pca.fit_transform(X)


In [3]:
#3.
from sklearn.decomposition import PCA

X = [[1, 2], [3, 4], [5, 6]]
pca = PCA(n_components=2)  # more components than features
X_new = pca.fit_transform(X)
X_new

array([[-2.82842712e+00, -4.74426853e-17],
       [ 0.00000000e+00, -0.00000000e+00],
       [ 2.82842712e+00, -4.74426853e-17]])

#4.
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

ratings = np.array([[5, 3, np.nan], [4, np.nan, 3]])

similarity = cosine_similarity(ratings)


In [4]:
#4.
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

ratings = np.array([[5, 3, np.nan], [4, np.nan, 3]])
ratings1 = np.nan_to_num(ratings)

similarity = cosine_similarity(ratings1)
similarity

array([[1.        , 0.68599434],
       [0.68599434, 1.        ]])

#5.
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

selector = RFE(estimator=LogisticRegression(), n_features_to_select=5)
selector.fit(X, y)  # Error: X and y not defined


In [5]:
#5.
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

X = [[1, 2, 3], [4, 0, 6], [7, 8, 9], [1, 2, 3]]
y = [0, 1, 0, 1]

selector = RFE(estimator=LogisticRegression(), n_features_to_select=5)
selector.fit(X, y)  # Error: X and y not defined


C:\Users\keert\anaconda3\Lib\site-packages\sklearn\feature_selection\_rfe.py:291: UserWarning: Found n_features_to_select=5 > n_features=3. There will be no feature selection and all features will be kept.
  warnings.warn(


RFE(estimator=LogisticRegression(), n_features_to_select=5)

#6.from sklearn.metrics.pairwise import cosine_similarity

items = ["action movie", "romantic comedy", "sci-fi thriller"]
similarity = cosine_similarity([items[0]], [items[1]])


In [6]:
#6.
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer

items = ["action movie", "romantic comedy", "sci-fi thriller"]
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(items)

similarity = cosine_similarity(X[0:1], X[1:2])
similarity



array([[0.]])

#7.
from sklearn.feature_selection import SelectKBest, f_classif

X = [[1, 2], [3, 4], [5, 6]]
y = [0, 1]  # Error: mismatched dimensions
selector = SelectKBest(score_func=f_classif, k=1)
X_new = selector.fit_transform(X, y)


In [7]:
#7.
from sklearn.feature_selection import SelectKBest, f_classif

X = [[1, 2], [3, 4], [5, 6]]
y = [0, 1,2]  # Error: mismatched dimensions
selector = SelectKBest(score_func=f_classif, k=1)
X_new = selector.fit_transform(X, y)
X_new

C:\Users\keert\anaconda3\Lib\site-packages\sklearn\feature_selection\_univariate_selection.py:109: RuntimeWarning: invalid value encountered in divide
  msw = sswn / float(dfwn)


array([[2],
       [4],
       [6]])

#8.
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

ratings = np.array([5, 4, 3])
cosine_similarity(ratings, ratings)


In [8]:
#8.
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

ratings = np.array([5, 4, 3]).reshape(1, -1)
cosine_similarity(ratings, ratings)


array([[1.]])

#9.
from sklearn.pipeline import Pipeline
from sklearn.feature_selection import SelectKBest, chi2

X = [[1, 2], [3, None], [4, 5]]
y = [0, 1, 0]

pipeline = Pipeline([
    ('select', SelectKBest(score_func=chi2, k=1))
])

pipeline.fit(X, y)


In [9]:
#9.
from sklearn.pipeline import Pipeline
from sklearn.feature_selection import SelectKBest, chi2
import numpy as np

X = [[1, 2], [3, np.nan], [4, 5]]
y = [0, 1, 0]

X=np.nan_to_num(X,nan=0.0)

pipeline = Pipeline([
    ('select', SelectKBest(score_func=chi2, k=1))
])

pipeline.fit(X, y)


Pipeline(steps=[('select',
                 SelectKBest(k=1,
                             score_func=<function chi2 at 0x000001BFAE407CE0>))])

#10.
from scipy.sparse import csr_matrix
from sklearn.feature_selection import SelectKBest, chi2

X = csr_matrix([[0, -1, 3], [0, 2, 1], [3, -1, 0]])
y = [0, 1, 0]

selector = SelectKBest(score_func=chi2, k=2)
X_new = selector.fit_transform(X, y)


In [10]:
#10.
from scipy.sparse import csr_matrix
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.preprocessing import MinMaxScaler

X = [[0, -1, 3], [0, 2, 1], [3, -1, 0]]
y = [0, 1, 0]

sc=MinMaxScaler()
x=sc.fit_transform(X)
selector = SelectKBest(score_func=chi2, k=2)
X_new = selector.fit_transform(x, y)
X_new

array([[0., 0.],
       [0., 1.],
       [1., 0.]])